### ISSUE TITLE
支持动态的batchsize输入吗？

### ISSUE THREAD

**Issue by Neroaway** [guojin-yan/TensorRTSharp#13]
`
predictor.SetBindingDimensions("images", new Dims(BatchSize, 3, 480, 640));
predictor.LoadInferenceData("images", inputDataBatch);
`
支持动态batchsize输入吗？因为有时候剪裁的图像数量并不一致

**Comment by Neroaway** [comment]
我的意思是，转成onnx engine的过程中，需要制定batchsize大小，有没有办法实现动态输入，不需要制定batchsize大小

**Comment by guojin-yan** [comment]
支持的，导出onnx模型的时候设置动态尺寸。
