### ISSUE TITLE
异常 ：尝试读取或写入受保护的内存

### ISSUE THREAD

**Issue by Neroaway** [guojin-yan/TensorRTSharp#14]
`public void LoadInferenceData(string nodeName, float[] data) 
        {
            sbyte[] nodeNameSbyte = (sbyte[])((Array)System.Text.Encoding.Default.GetBytes(nodeName));
            HandleException.Handler(NativeMethods.copyFloatHostToDeviceByName(ptr, ref nodeNameSbyte[0], ref data[0]));
        } `
我代码跑了一段时间提示异常： predictor.LoadInferenceData("images", inputDataBatch); 提示异常：尝试读取或写入受保护的内存。这个是指针的问题吗？

**Comment by guojin-yan** [comment]
Check if the data length matches the model input.
