### ISSUE TITLE
serializationVersion 问题

### ISSUE THREAD

**Issue by Neroaway** [guojin-yan/TensorRTSharp#8]
编译完dll之后，C#读取Nvinfer predictor = new Nvinfer(@"*/best.engine");提示异常TensorRtSharp.Internal.PInvoke.TRTException:“[stdArchiveReader.cpp::nvinfer1::rt::StdArchiveReader::StdArchiveReaderInitCommon::46] Error Code 1: Serialization (Serialization assertion stdVersionRead == serializationVersion failed.Version tag does not match. Note: Current Version: 236, Serialized Engine Version: 237)”，这个怎么解决哇~

**Comment by guojin-yan** [comment]
模型是否是在本机使用本项目提供的接口转换的？如果不是，请重新转换

**Comment by Neroaway** [comment]
谢谢：），刚刚解决了，是tensorrt版本python和C#使用版本不一致的问题
