### ISSUE TITLE
TensorRtExtern.dll or one of its dependencies: 找不到指定的模組。 (0x8007007E)

### ISSUE THREAD

**Issue by seenew** [guojin-yan/TensorRTSharp#9]
感謝您貢獻分享此專案

我在成功編譯 TensorRtExtern.dll 後
並確定專案指定 TensorRtExtern.dll 路徑正確 ( NativeMethods.tensorrt_dll_path 指定路徑 )

運行程序後都會報錯  TensorRtExtern.dll or one of its dependencies: 找不到指定的模組。 (0x8007007E)

請問 TensorRtExtern.dll 需要其他相依性的 dll 嗎  謝謝

**Comment by guojin-yan** [comment]
出现这种原因主要是因为没有配置对生成dll文件的C++项目，导致调用的时候找不到依赖。，有问题可以入群交流，QQ群：945057948

**Comment by seenew** [comment]
感謝您回覆
因為在台灣沒法註冊QQ (需要手機與實名認證. 實在殘念)

我在針對您建議部分嘗試看看

謝謝
